### ISSUE TITLE
how to run this app?

### ISSUE THREAD

**Issue by suipinglu** [johnhutch/rails3starter#1]
hi, i try to run this app. but got this and dont know how to fix this. 

do you have any idea about this ?? thanks so much.

rvm/gems/ruby-1.9.3-p362/gems/json-1.7.6/lib/json/ext/parser.bundle: [BUG] Segmentation fault
ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0]

**Comment by johnhutch** [comment]
Hey there, 

Please note the .rvmrc included with the project. Looks like you're using system ruby, 1.87. I've currently optimized for ruby-1.9.3-p194. If you install rvm on your system, when you cd into the directory, it should prompt you to install p194 and the gemset "tinder" for all tinder-related gems.

Instructions on installing rvm (it's super easy) can be found here: https://rvm.io/

**Comment by suipinglu** [comment]
yep, thank you. you are right. but i dont know why when i enter into your project, it uses the 1.8.7 which is the oldest version of ruby i got from mac. but i got the rvm and update my ruby to 1.9.3 already. btw, do i need to run this every time "rvm gemset create tinder" after i switch off my laptop and "bundle install", some of the gem are repeating install again...did i do something wrong?? cheers

**Comment by johnhutch** [comment]
Make sure you actually install ruby-1.9.3-p194, as opposed to ruby-1.9.3-p362. I should be releasing an update relatively soon for p362, but in the  meantime, the .rvmrc demands p194. If you don't have that in your rubies (rvm list), that could be why you're falling back to system ruby (1.8.7). 

You shouldn't have to create the tinder gemset more than once. If you are, that may be why you're getting repeated installs. Once you have your correct ruby and the tinder gemset, when you cd into the Tinder project folder, you shouldn't get any rvmrc warnings. Do a quick bundle install or bundle update to make sure you're up to date and then you're good to go.

**Comment by johnhutch** [comment]
Note that if you created a gemset with rails 1.8.7, and you want to create a new gemset of the same name under rails 1.9.3, you'll need to delete the old gemset, or it'll keep asking you to create it.
